## Урок 7

## Линейная регрессия. Двухвыборочный t-тест. A/B-тестирование

В поле ответа впишите одно число. Нецелые числа следует округлить до 8 знаков после запятой.

__Задача 1__

Дана матрица объект-признак
```
X = [[ 1.22401313,  2.30868478,  3.03636353,  2.69287214],
     [-0.18757272,  1.30337355,  5.12093014,  3.46363202],
     [-0.81094525,  1.82463398,  5.79686488,  1.86159445],
     [ 0.75129018,  2.67392052,  3.65529809,  1.66746094],
     [ 0.00972362,  1.97367255,  2.50594319,  1.69755173],
     [-0.62972637,  0.77750764,  2.84124027,  4.54410559],
     [ 2.29536229,  1.81206697,  1.95026215,  1.51874636],
     [ 0.0920418 ,  2.26971361,  7.47708735,  2.61081203],
     [ 2.39252799,  3.17563985,  3.61420599,  5.10773362],
     [ 0.54983815,  2.87988651,  1.65752765,  1.59635987]]
```
и значения целевой переменной
```
y = [ 9.26193358,  9.700363  ,  8.67214805,  8.74796974,  6.18689108,
      7.53312713,  7.57643777, 12.44965478, 14.29010746,  6.68361218]
```

Подберите два признака (из четырёх) так, чтобы уровень линейной зависимости целевой переменной от значений этих признаков был максимальным. Другими словами, модель линейной регрессии на этих признаках должна давать наилучший результат. В качестве ответа запишите значение коэффициента детерминации для модели на этих признаках.

In [32]:
import numpy as np

In [34]:
x = np.array([[ 1.22401313,  2.30868478,  3.03636353,  2.69287214],
     [-0.18757272,  1.30337355,  5.12093014,  3.46363202],
     [-0.81094525,  1.82463398,  5.79686488,  1.86159445],
     [ 0.75129018,  2.67392052,  3.65529809,  1.66746094],
     [ 0.00972362,  1.97367255,  2.50594319,  1.69755173],
     [-0.62972637,  0.77750764,  2.84124027,  4.54410559],
     [ 2.29536229,  1.81206697,  1.95026215,  1.51874636],
     [ 0.0920418 ,  2.26971361,  7.47708735,  2.61081203],
     [ 2.39252799,  3.17563985,  3.61420599,  5.10773362],
     [ 0.54983815,  2.87988651,  1.65752765,  1.59635987]])

y = np.array([ 9.26193358,  9.700363  ,  8.67214805,  8.74796974,  6.18689108, 
     7.53312713,  7.57643777, 12.44965478, 14.29010746,  6.68361218])

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
x1 = x[:, [0,2]] # выбираем два признака из четерех
x1

array([[ 1.22401313,  3.03636353],
       [-0.18757272,  5.12093014],
       [-0.81094525,  5.79686488],
       [ 0.75129018,  3.65529809],
       [ 0.00972362,  2.50594319],
       [-0.62972637,  2.84124027],
       [ 2.29536229,  1.95026215],
       [ 0.0920418 ,  7.47708735],
       [ 2.39252799,  3.61420599],
       [ 0.54983815,  1.65752765]])

In [37]:
lr = LinearRegression(fit_intercept=True).fit(x1, y)

In [38]:
b = lr.coef_
b

array([1.62531203, 1.21134979])

In [39]:
e = y - x1.dot(b)
e

array([3.59443198, 3.80198953, 2.96815605, 3.09904419, 3.1355134 ,
       5.11489316, 1.48330817, 3.24268992, 6.02343525, 3.78210784])

In [40]:
r2 = 1 - ((e - e.mean()) ** 2).sum() / ((y - y.mean()) ** 2).sum()
r2

0.763424623879315

In [41]:
print(f"Ответ: R2 = {np.round(r2, 8)}")

Ответ: R2 = 0.76342462


__Задача 2__

Является ли значимым уравнение регрессии, полученное в предыдущей задаче? В качестве ответа запишите 1, если является, и 0 иначе.


In [42]:
from scipy import stats

In [43]:
a = 0.05
n = x1.shape[0]
m = x1.shape[1]

k1 = m
k2 = n - m - 1

k1, k2

(2, 7)

In [44]:
F = (r2 / k1) / ((1 - r2) / k2)
F

11.294439122922636

In [45]:
t = stats.f.ppf(1 - a, k1, k2)
t

4.73741412777588

In [46]:
F > t

True

__Ответ: 1, так как статистика F попала в критическую область > t.__

__Задача 3__

Для проведения A/B-тестирования сайта интернет-магазина были получены следующие данные: страница `A` была посещена 2509 раз, из них 77 закончились совершением покупки, страница `B` была посещена 1465 раз, 60 из них закончились совершением покупки. Является ли значимым отличие конверсии на страницах `A` и `B`? В качестве ответа запишите 1, если является, и 0 иначе.

_Подсказка_. Реализуйте двухвыборочный t-тест. В качестве выборок здесь можно взять наборы меток совершения покупки (0 или 1) каждым посетителем.

In [50]:
a = 0.05

In [61]:
n1 = 2509
n2 = 1465

In [62]:
x1 = np.hstack((np.zeros(n1 - 77), np.ones(77)))
x2 = np.hstack((np.zeros(n2 - 60), np.ones(60)))

In [63]:
std1 = x1.std(ddof=1)
std2 = x2.std(ddof=1)

std1, std2

(0.17250951379621338, 0.19825513126725994)

In [53]:
std_d = np.sqrt(std1 ** 2 / n1 + std2 ** 2 / n2)
std_d

0.006220171278295827

In [68]:
t = (x1.mean() - x2.mean()) / std_d
t

-1.6504551408398205

In [69]:
df = (std1 ** 2 / n1 + std2 ** 2 / n2) ** 2 / \
    ((std1 ** 2 / n1) ** 2 / (n1 - 1) + (std2 ** 2 / n2) ** 2 / (n2 - 1))

df

2732.8025644352133

In [70]:
t1 = stats.t.ppf(a / 2, df=df)
t2 = stats.t.ppf(1 - a / 2, df=df)

t1, t2

(-1.9608324352746576, 1.9608324352746571)

In [71]:
t1 < t < t2

True

Значение статистики не попало в критическую область, следовательно утверждение о значимости конверсий ложное.

In [73]:
stats.ttest_ind(x1, x2, equal_var=False) # проверка в готовой реализации

Ttest_indResult(statistic=-1.6504551408398205, pvalue=0.09896479217925898)

__Ответ: 0__